moo_sources +=					\
	eggsmclient/eggsmclient.c		\
	eggsmclient/eggsmclient.h		\
	eggsmclient/eggsmclient-mangle.h	\
	eggsmclient/eggsmclient-private.h

AM_CFLAGS += -DEGG_SM_CLIENT_BACKEND_XSMP
moo_sources += eggsmclient/eggsmclient-xsmp.c eggsmclient/eggdesktopfile.h eggsmclient/eggdesktopfile.c

# -%- strip:true -%-
