moo_sources +=			\
	mooapp/mooapp.c		\
	mooapp/mooapp.h		\
	mooapp/mooapp-accels.h	\
	mooapp/mooapp-info.h	\
	mooapp/mooapp-private.h	\
	mooapp/moohtml.h	\
	mooapp/moohtml.cpp	\
	mooapp/moolinklabel.h	\
	mooapp/moolinklabel.c	\
	mooapp/credits.h	\
	mooapp/credits.c	\
	mooapp/about.h		\
	mooapp/about.c

# FIXME: use resources
built_moo_sources += mooapp-credits.h
mooapp-credits.h: $(top_srcdir)/THANKS $(top_srcdir)/tools/xml2h.py
	$(AM_V_GEN)$(MOO_PYTHON) $(top_srcdir)/tools/xml2h.py $(top_srcdir)/THANKS mooapp-credits.h MOO_APP_CREDITS
