plugins_sources +=					\
	plugins/usertools/moousertools.cpp		\
	plugins/usertools/moousertools.h		\
	plugins/usertools/moousertools-prefs.cpp	\
	plugins/usertools/moousertools-prefs.h		\
	plugins/usertools/moocommand.cpp		\
	plugins/usertools/moocommand.h			\
	plugins/usertools/moocommand-private.h		\
	plugins/usertools/moocommanddisplay.cpp		\
	plugins/usertools/moocommanddisplay.h		\
	plugins/usertools/moooutputfilterregex.cpp	\
	plugins/usertools/moooutputfilterregex.h	\
	plugins/usertools/moousertools-enums.h		\
	plugins/usertools/moousertools-enums.cpp	\
	plugins/usertools/moocommand-exe.cpp		\
	plugins/usertools/moocommand-exe.h

EXTRA_DIST +=						\
	plugins/usertools/glade/mooedittools-exe.glade	\
	plugins/usertools/glade/moousertools.glade

built_plugins_sources +=				\
	plugins/usertools/mooedittools-exe-gxml.h	\
	plugins/usertools/moousertools-gxml.h

cfgdir = $(MOO_DATA_DIR)
cfg_DATA =					\
	plugins/usertools/filters.xml		\
	plugins/usertools/menu.xml		\
	plugins/usertools/context.xml
EXTRA_DIST +=					\
	plugins/usertools/filters.xml		\
	plugins/usertools/menu-tmpl.xml		\
	plugins/usertools/context-tmpl.xml	\
	plugins/usertools/genplatxml.py

genplatxml_args =
genplatxml_args += --enable=unix

built_plugins_sources += plugins/usertools/menu.xml plugins/usertools/context.xml
plugins/usertools/%.xml: plugins/usertools/%-tmpl.xml plugins/usertools/genplatxml.py
	$(AM_V_at)$(MKDIR_P) plugins/usertools
	$(AM_V_GEN)$(MOO_PYTHON) $(srcdir)/plugins/usertools/genplatxml.py $(genplatxml_args) \
		$(srcdir)/plugins/usertools/$*-tmpl.xml > $@.tmp && mv $@.tmp $@
