EXTRA_DIST += medit-app/medit.desktop.in

if MOO_BUILD_APP

bin_PROGRAMS += medit

medit_SOURCES =				\
	medit-app/main.h		\
	medit-app/main.cpp		\
	$(moo_sources)			\
	$(plugins_sources)

nodist_EXTRA_medit_SOURCES =		\
	dummy.cpp

medit_LDADD = $(MOO_LIBS) $(moo_libadd)

nodist_medit_SOURCES =			\
	$(built_moo_sources)		\
	$(built_plugins_sources)

medit_LDFLAGS =

if MOO_OS_UNIX
desktopdir = $(datadir)/applications
desktop_DATA = medit-app/medit.desktop
medit-app/medit.desktop: medit-app/medit.desktop.in @MOO_INTLTOOL_INI_DEPS@
	$(AM_V_at)$(MKDIR_P) medit-app
	@MOO_INTLTOOL_INI_CMD@
CLEANFILES += medit-app/medit.desktop
endif MOO_OS_UNIX

iconthemedir = $(datadir)/icons/hicolor/48x48/apps
icontheme_DATA = mooutils/pixmaps/medit.png
if MOO_ENABLE_INSTALL_HOOKS
update_icon_cache = gtk-update-icon-cache -f -t $(DESTDIR)$(datadir)/icons/hicolor
install-data-hook: install-data-hook-gtk-icon-cache
install-data-hook-gtk-icon-cache:
	@if echo "Updating icon cache" && $(update_icon_cache); then		\
		echo "Done.";							\
	else									\
		echo "*** GTK icon cache not updated. After install, run this:";\
		echo $(update_icon_cache);					\
	fi
uninstall-hook: uninstall-data-hook-gtk-icon-cache
uninstall-data-hook-gtk-icon-cache:
	@if echo "Updating icon cache" && $(update_icon_cache); then echo "Done."; else echo "Failed."; fi
endif

endif MOO_BUILD_APP
