source_files = \
    ../src/mooapp/about.c\
    ../src/mooapp/about.h\
    ../src/mooapp/credits.c\
    ../src/mooapp/credits.h\
    ../src/mooapp/mooapp-accels.h\
    ../src/mooapp/mooapp.c\
    ../src/mooapp/mooapp.h\
    ../src/mooapp/mooapp-info.h\
    ../src/mooapp/mooapp-private.h\
    ../src/mooedit/mooedit-accels.h\
    ../src/mooedit/mooeditaction.cpp\
    ../src/mooedit/mooeditaction-factory.cpp\
    ../src/mooedit/mooeditaction-factory.h\
    ../src/mooedit/mooeditaction.h\
    ../src/mooedit/mooeditbookmark.cpp\
    ../src/mooedit/mooeditbookmark.h\
    ../src/mooedit/mooedit.cpp\
    ../src/mooedit/mooeditconfig.cpp\
    ../src/mooedit/mooeditconfig.h\
    ../src/mooedit/mooeditdialogs.cpp\
    ../src/mooedit/mooeditdialogs.h\
    ../src/mooedit/mooedit-enum-types.c\
    ../src/mooedit/mooedit-enum-types.h\
    ../src/mooedit/mooedit-enums.h\
    ../src/mooedit/mooeditfileinfo.cpp\
    ../src/mooedit/mooeditfileinfo.h\
    ../src/mooedit/mooedit-fileops.cpp\
    ../src/mooedit/mooedit-fileops.h\
    ../src/mooedit/mooeditfiltersettings.cpp\
    ../src/mooedit/mooeditfiltersettings.h\
    ../src/mooedit/mooedit.h\
    ../src/mooedit/mooedithistoryitem.cpp\
    ../src/mooedit/mooedithistoryitem.h\
    ../src/mooedit/mooedit-impl.h\
    ../src/mooedit/mooeditor.cpp\
    ../src/mooedit/mooeditor.h\
    ../src/mooedit/mooeditor-impl.h\
    ../src/mooedit/mooeditor-private.h\
    ../src/mooedit/mooeditprefs.cpp\
    ../src/mooedit/mooeditprefs.h\
    ../src/mooedit/mooeditprefspage.cpp\
    ../src/mooedit/mooedit-private.h\
    ../src/mooedit/mooedit-script.cpp\
    ../src/mooedit/mooedit-script.h\
    ../src/mooedit/mooedittab.cpp\
    ../src/mooedit/mooedittab.h\
    ../src/mooedit/mooedittypes.h\
    ../src/mooedit/mooeditview.cpp\
    ../src/mooedit/mooeditview.h\
    ../src/mooedit/mooeditview-script.cpp\
    ../src/mooedit/mooeditview-script.h\
    ../src/mooedit/mooeditwindow.cpp\
    ../src/mooedit/mooeditwindow.h\
    ../src/mooedit/mooeditwindow-impl.h\
    ../src/mooedit/moofold.cpp\
    ../src/mooedit/moofold.h\
    ../src/mooedit/mooindenter.cpp\
    ../src/mooedit/mooindenter.h\
    ../src/mooedit/moolang.cpp\
    ../src/mooedit/moolang.h\
    ../src/mooedit/moolangmgr.cpp\
    ../src/mooedit/moolangmgr.h\
    ../src/mooedit/moolangmgr-private.h\
    ../src/mooedit/moolang-private.h\
    ../src/mooedit/moolinebuffer.c\
    ../src/mooedit/moolinebuffer.h\
    ../src/mooedit/moolinemark.c\
    ../src/mooedit/moolinemark.h\
    ../src/mooedit/mooplugin.c\
    ../src/mooedit/mooplugin.h\
    ../src/mooedit/mooplugin-loader.c\
    ../src/mooedit/mooplugin-loader.h\
    ../src/mooedit/mooplugin-macro.h\
    ../src/mooedit/mootextbtree.c\
    ../src/mooedit/mootextbtree.h\
    ../src/mooedit/mootextbuffer.c\
    ../src/mooedit/mootextfind.c\
    ../src/mooedit/mootextfind.h\
    ../src/mooedit/mootextiter.h\
    ../src/mooedit/mootextprint.c\
    ../src/mooedit/mootextprint.h\
    ../src/mooedit/mootextprint-private.h\
    ../src/mooedit/mootext-private.h\
    ../src/mooedit/mootextsearch.c\
    ../src/mooedit/mootextsearch.h\
    ../src/mooedit/mootextsearch-private.h\
    ../src/mooedit/mootextstylescheme.c\
    ../src/mooedit/mootextstylescheme.h\
    ../src/mooedit/mootextview.c\
    ../src/mooedit/mootextview.h\
    ../src/mooedit/mootextview-input.c\
    ../src/mooedit/mootextview-private.h\
    ../src/moofileview/moobookmarkmgr.c\
    ../src/moofileview/moobookmarkmgr.h\
    ../src/moofileview/moobookmarkview.c\
    ../src/moofileview/moobookmarkview.h\
    ../src/moofileview/moofile.c\
    ../src/moofileview/moofileentry.c\
    ../src/moofileview/moofileentry.h\
    ../src/moofileview/moofile.h\
    ../src/moofileview/moofile-private.h\
    ../src/moofileview/moofilesystem.c\
    ../src/moofileview/moofilesystem.h\
    ../src/moofileview/moofileview-accels.h\
    ../src/moofileview/moofileview-aux.h\
    ../src/moofileview/moofileview.c\
    ../src/moofileview/moofileview-dialogs.c\
    ../src/moofileview/moofileview-dialogs.h\
    ../src/moofileview/moofileview.h\
    ../src/moofileview/moofileview-impl.h\
    ../src/moofileview/moofileview-private.h\
    ../src/moofileview/moofileview-tools.cpp\
    ../src/moofileview/moofileview-tools.h\
    ../src/moofileview/moofolder.c\
    ../src/moofileview/moofolder.h\
    ../src/moofileview/moofoldermodel.c\
    ../src/moofileview/moofoldermodel.h\
    ../src/moofileview/moofoldermodel-private.h\
    ../src/moofileview/moofolder-private.h\
    ../src/moofileview/mooiconview.c\
    ../src/moofileview/mooiconview.h\
    ../src/moofileview/mootreeview.c\
    ../src/moofileview/mootreeview.h\
    ../src/mooutils/mooaccelbutton.c\
    ../src/mooutils/mooaccelbutton.h\
    ../src/mooutils/mooaccel.cpp\
    ../src/mooutils/mooaccel.h\
    ../src/mooutils/mooaccelprefs.cpp\
    ../src/mooutils/mooaccelprefs.h\
    ../src/mooutils/mooactionbase.c\
    ../src/mooutils/mooactionbase.h\
    ../src/mooutils/mooactionbase-private.h\
    ../src/mooutils/mooaction.c\
    ../src/mooutils/mooactioncollection.c\
    ../src/mooutils/mooactioncollection.h\
    ../src/mooutils/mooactionfactory.c\
    ../src/mooutils/mooactionfactory.h\
    ../src/mooutils/mooactiongroup.c\
    ../src/mooutils/mooactiongroup.h\
    ../src/mooutils/mooaction.h\
    ../src/mooutils/mooaction-private.h\
    ../src/mooutils/mooappinput-common.c\
    ../src/mooutils/mooappinput.h\
    ../src/mooutils/mooapp-ipc.c\
    ../src/mooutils/mooapp-ipc.h\
    ../src/mooutils/mooarray.h\
    ../src/mooutils/mooatom.h\
    ../src/mooutils/moobigpaned.c\
    ../src/mooutils/moobigpaned.h\
    ../src/mooutils/mooclosure.c\
    ../src/mooutils/mooclosure.h\
    ../src/mooutils/moocombo.c\
    ../src/mooutils/moocombo.h\
    ../src/mooutils/moocompat.h\
    ../src/mooutils/moodialogs.c\
    ../src/mooutils/moodialogs.h\
    ../src/mooutils/mooeditops.c\
    ../src/mooutils/mooeditops.h\
    ../src/mooutils/mooencodings.cpp\
    ../src/mooutils/mooencodings-data.h\
    ../src/mooutils/mooencodings.h\
    ../src/mooutils/mooentry.cpp\
    ../src/mooutils/mooentry.h\
    ../src/mooutils/moo-environ.h\
    ../src/mooutils/moofiledialog.c\
    ../src/mooutils/moofiledialog.h\
    ../src/mooutils/moofileicon.c\
    ../src/mooutils/moofileicon.h\
    ../src/mooutils/moofilewatch.c\
    ../src/mooutils/moofilewatch.h\
    ../src/mooutils/moofilewriter.cpp\
    ../src/mooutils/moofilewriter.h\
    ../src/mooutils/moofilewriter-private.h\
    ../src/mooutils/moofiltermgr.c\
    ../src/mooutils/moofiltermgr.h\
    ../src/mooutils/moofontsel.c\
    ../src/mooutils/moofontsel.h\
    ../src/mooutils/mooglade.c\
    ../src/mooutils/mooglade.h\
    ../src/mooutils/moohelp.c\
    ../src/mooutils/moohelp.h\
    ../src/mooutils/moohistorycombo.c\
    ../src/mooutils/moohistorycombo.h\
    ../src/mooutils/moohistorylist.c\
    ../src/mooutils/moohistorylist.h\
    ../src/mooutils/moohistorymgr.c\
    ../src/mooutils/moohistorymgr.h\
    ../src/mooutils/mooi18n.cpp\
    ../src/mooutils/mooi18n.h\
    ../src/mooutils/moolist.h\
    ../src/mooutils/moomarkup.c\
    ../src/mooutils/moomarkup.h\
    ../src/mooutils/moomenuaction.c\
    ../src/mooutils/moomenuaction.h\
    ../src/mooutils/moomenu.c\
    ../src/mooutils/moomenu.h\
    ../src/mooutils/moomenumgr.c\
    ../src/mooutils/moomenumgr.h\
    ../src/mooutils/moomenutoolbutton.c\
    ../src/mooutils/moomenutoolbutton.h\
    ../src/mooutils/moo-mime.c\
    ../src/mooutils/moo-mime.h\
    ../src/mooutils/moonotebook.c\
    ../src/mooutils/moonotebook.h\
    ../src/mooutils/mooonce.h\
    ../src/mooutils/moopane.c\
    ../src/mooutils/moopaned.c\
    ../src/mooutils/moopaned.h\
    ../src/mooutils/moopane.h\
    ../src/mooutils/mooprefs.c\
    ../src/mooutils/mooprefsdialog.c\
    ../src/mooutils/mooprefsdialog.h\
    ../src/mooutils/mooprefs.h\
    ../src/mooutils/mooprefspage.c\
    ../src/mooutils/mooprefspage.h\
    ../src/mooutils/moospawn.c\
    ../src/mooutils/moospawn.h\
    ../src/mooutils/moostock.c\
    ../src/mooutils/moostock.h\
    ../src/mooutils/mootype-macros.h\
    ../src/mooutils/moouixml.c\
    ../src/mooutils/moouixml.h\
    ../src/mooutils/mooundo.c\
    ../src/mooutils/mooundo.h\
    ../src/mooutils/mooutils-debug.h\
    ../src/mooutils/mooutils-enums.c\
    ../src/mooutils/mooutils-enums.h\
    ../src/mooutils/mooutils-file.c\
    ../src/mooutils/mooutils-file.h\
    ../src/mooutils/mooutils-fs.cpp\
    ../src/mooutils/mooutils-fs.h\
    ../src/mooutils/mooutils-gobject.cpp\
    ../src/mooutils/mooutils-gobject.h\
    ../src/mooutils/mooutils-gobject-private.h\
    ../src/mooutils/mooutils.h\
    ../src/mooutils/mooutils-macros.h\
    ../src/mooutils/mooutils-mem.h\
    ../src/mooutils/mooutils-messages.h\
    ../src/mooutils/mooutils-misc.cpp\
    ../src/mooutils/mooutils-misc.h\
    ../src/mooutils/mooutils-script.c\
    ../src/mooutils/mooutils-script.h\
    ../src/mooutils/mooutils-treeview.cpp\
    ../src/mooutils/mooutils-treeview.h\
    ../src/mooutils/moowindow.c\
    ../src/mooutils/moowindow.h\
    ../src/plugins/support/moocmdview.cpp\
    ../src/plugins/support/moocmdview.h\
    ../src/plugins/support/mooeditwindowoutput.cpp\
    ../src/plugins/support/mooeditwindowoutput.h\
    ../src/plugins/support/moolineview.cpp\
    ../src/plugins/support/moolineview.h\
    ../src/plugins/support/moooutputfilter.cpp\
    ../src/plugins/support/moooutputfilter.h\
    ../src/plugins/usertools/moocommand.cpp\
    ../src/plugins/usertools/moocommanddisplay.cpp\
    ../src/plugins/usertools/moocommanddisplay.h\
    ../src/plugins/usertools/moocommand.h\
    ../src/plugins/usertools/moocommand-private.h\
    ../src/plugins/usertools/moooutputfilterregex.cpp\
    ../src/plugins/usertools/moooutputfilterregex.h\
    ../src/plugins/usertools/moousertools.cpp\
    ../src/plugins/usertools/moousertools-enums.cpp\
    ../src/plugins/usertools/moousertools-enums.h\
    ../src/plugins/usertools/moousertools.h\
    ../src/plugins/usertools/moousertools-prefs.cpp\
    ../src/plugins/usertools/moousertools-prefs.h
